name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk unzip wget zip
          pip install --upgrade pip
          pip install cython kivy buildozer

      - name: Accept Android SDK licenses and install build-tools
        run: |
          yes | buildozer android sdk --install
          yes | buildozer android update

      - name: Build APK
        run: |
          cd ${{ github.workspace }}
          buildozer android debug
