name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: kivy/buildozer:latest

    steps:
      - uses: actions/checkout@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Python dependencies
        run: pip install cython kivy requests

      - name: Build APK
        run: buildozer android debug
