name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository'i çek
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Temel bağımlılıkları yükle
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev openjdk-17-jdk zip unzip tar zlib1g-dev \
          libncurses5 libncurses5-dev libffi-dev libssl-dev git wget curl
          pip3 install --upgrade pip
          pip3 install buildozer cython kivy

      # 3. Buildozer ile APK inşasını başlat
      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer android debug

      # 4. Üretilen APK'yı artifact olarak sakla
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: bin/*.apk
