name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repo çek
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Sistem bağımlılıklarını yükle (güncel paketler)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev openjdk-17-jdk zip unzip tar zlib1g-dev \
          libffi-dev libssl-dev git wget curl default-jdk
          pip3 install --upgrade pip
          pip3 install buildozer cython kivy

      # 3. APK inşası
      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer android debug

      # 4. APK’yı artifact olarak sakla
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
